name: CI / TypeCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: rm -f package-lock.json && npm install
      - name: TypeCheck / Lint
        run: npm run lint
      - name: Build
        run: npm run build
